package io.github.triploit.parser.token;

/**
 * Created by survari on 14.04.17.
 */
public class TokenType
{
	public enum TOKEN_TYPES
	{
		TAG,
		ATTRIBUTE,
		BRACE_OPEN,
		BRACE_CLOSE,
		PARENTHIS_OPEN,
		PARENTHIS_CLOSE,
		DOUBLE_POINT,
		NEW_LINE,
		WORD,
		COMMA
	}

	public static final TOKEN_TYPES getRightType(String value)
	{
		value = value.trim();

		if (value.equals("{"))
			return TOKEN_TYPES.BRACE_OPEN;
		else if (value.equals("}"))
			return TOKEN_TYPES.BRACE_CLOSE;
		else if (existsTag(value))
			return TOKEN_TYPES.TAG;
		else if (existsAttribute(value))
			return TOKEN_TYPES.ATTRIBUTE;
		else if (value.equals("("))
			return TOKEN_TYPES.PARENTHIS_OPEN;
		else if (value.equals(")"))
			return TOKEN_TYPES.PARENTHIS_CLOSE;
		else if (value.equals(":"))
			return TOKEN_TYPES.DOUBLE_POINT;
		else if (value.equals(","))
			return TOKEN_TYPES.COMMA;
		else
			return TOKEN_TYPES.WORD;
	}

	public static final boolean existsTag(String value)
	{
		value = value.trim().toLowerCase();

		for (String word : TAG_LIST)
		{
			if (word.trim().equals(value))
				return true;
		}

		return false;
	}

	public static final boolean existsAttribute(String value)
	{
		value = value.trim().toLowerCase();

		for (String[] word : ATTRIBUTE_LIST)
		{
			if (word[0].trim().equals(value))
				return true;
		}

		return false;
	}

	public static final boolean isRightAttribut(String attribut, String tag)
	{
		if (!existsAttribute(attribut) ||
				!existsTag(tag))
			return false;

		for (String[] words : ATTRIBUTE_LIST)
		{
			for (String word : words)
			{
				if (words[0].equals(attribut))
				{
					if (words[1].equals("*") ||
							word.equals(tag))
						return true;
				}
			}
		}

		return false;
	}

	private static final String[] TAG_LIST = {
			"html",
			"head",
			"body",
			"div",
			"link",
			"script",
			"h1",
			"h3",
			"h2",
			"h4",
			"h5",
			"h6",
			"b",
			"strong",
			"sup",
			"sub",
			"del",
			"del",
			"ins",
			"small",
			"a",
			"li",
			"ul",
			"ol",
			"span",
			"style",
			"noscript",
			"header",
			"address",
			"main",
			"pre",
			"il",
			"dl",
			"dt",
			"dd",
			"figure",
			"figcaption",
			"s",
			"cite",
			"q",
			"dfn",
			"abbr",
			"code",
			"var",
			"data",
			"time",
			"samp",
			"i",
			"b",
			"u",
			"img",
			"object",
			"embed",
			"iframe",
			"param",
			"audio",
			"video",
			"source",
			"canvas",
			"track",
			"map",
			"area",
			"svg",
			"math",
			"table",
			"caption",
			"colgroup",
			"col",
			"tbody",
			"thead",
			"tfoot",
			"tr",
			"td",
			"th",
			"form",
			"fieldset",
			"legend",
			"label",
			"input",
			"button",
			"select",
			"datalist",
			"optgroup",
			"option",
			"textarea",
			"keygen",
			"output",
			"progress",
			"meter",
			"details",
			"summary",
			"command",
			"menu",
			"meta",
			"br",
			"hr",
			"p",
	        "title"
	};

	private static final String[][] ATTRIBUTE_LIST = { // Attribute, Tag, Tag2, Tag3, ...
	                                                  {
			                                                  "accept",
			                                                  "form",
			                                                  "input"
	                                                  },
	                                                  {
			                                                  "accept-charset",
			                                                  "form"
	                                                  },
	                                                  {
			                                                  "acceskey",
			                                                  "*"
	                                                  },
	                                                  {
			                                                  "action",
			                                                  "form"
	                                                  },
	                                                  {
			                                                  "align",
			                                                  "applet",
			                                                  "caption",
			                                                  "col",
			                                                  "colgroup",
			                                                  "gr",
			                                                  "iframe",
			                                                  "img",
			                                                  "table",
			                                                  "tbody",
			                                                  "td",
			                                                  "tfoot",
			                                                  "th",
			                                                  "thead",
			                                                  "tr"
	                                                  },
	                                                  {
			                                                  "alt",
			                                                  "applet",
			                                                  "area",
			                                                  "img",
			                                                  "input"
	                                                  },
	                                                  {
			                                                  "async",
			                                                  "script"
	                                                  },
	                                                  {
			                                                  "autocomplete",
			                                                  "form",
			                                                  "input"
	                                                  },
	                                                  {
			                                                  "autofocus",
			                                                  "button",
			                                                  "keygen",
			                                                  "select",
			                                                  "input",
			                                                  "textarea"
	                                                  },
	                                                  {
			                                                  "autoplay",
			                                                  "audio",
			                                                  "video"
	                                                  },
	                                                  {
			                                                  "autosave",
			                                                  "input"
	                                                  },
	                                                  {
			                                                  "bgcolor",
			                                                  "body",
			                                                  "col",
			                                                  "colgroup",
			                                                  "marquee",
			                                                  "table",
			                                                  "tbody",
			                                                  "tfoot",
			                                                  "td",
			                                                  "th",
			                                                  "tr"
	                                                  },
	                                                  {
			                                                  "border",
			                                                  "img",
			                                                  "object",
			                                                  "table"
	                                                  },
	                                                  {
			                                                  "buffered",
			                                                  "audio",
			                                                  "video"
	                                                  },
	                                                  {
			                                                  "challenge",
			                                                  "keygen"
	                                                  },
	                                                  {
			                                                  "charset",
			                                                  "meta",
			                                                  "script"
	                                                  },
	                                                  {
			                                                  "checked",
			                                                  "command",
			                                                  "input"
	                                                  },
	                                                  {
			                                                  "cite",
			                                                  "blockquote",
			                                                  "del",
			                                                  "ins",
			                                                  "q"
	                                                  },
	                                                  {
			                                                  "class",
			                                                  "*"
	                                                  },
	                                                  {
			                                                  "codebase",
			                                                  "applet"
	                                                  },
	                                                  {
			                                                  "code",
			                                                  "applet"
	                                                  },
	                                                  {
			                                                  "color",
			                                                  "basefont",
			                                                  "font",
			                                                  "hr"
	                                                  },
	                                                  {
			                                                  "cols",
			                                                  "textarea"
	                                                  },
	                                                  {
			                                                  "colspan",
			                                                  "td",
			                                                  "th"
	                                                  },
	                                                  {
			                                                  "content",
			                                                  "meta"
	                                                  },
	                                                  {
			                                                  "contenteditable",
			                                                  "*"
	                                                  },
	                                                  {
			                                                  "contextmenu",
			                                                  "*"
	                                                  },
	                                                  {
			                                                  "controls",
			                                                  "video",
			                                                  "audio"
	                                                  },
	                                                  {
			                                                  "coords",
			                                                  "area"
	                                                  },
	                                                  {
			                                                  "crossorigin",
			                                                  "audio",
			                                                  "img",
			                                                  "link",
			                                                  "script",
			                                                  "video"
	                                                  },
	                                                  {
			                                                  "data",
			                                                  "object"
	                                                  },
	                                                  {
			                                                  "data-*",
			                                                  "*"
	                                                  },
	                                                  {
			                                                  "datetime",
			                                                  "del",
			                                                  "ins",
			                                                  "time"
	                                                  },
	                                                  {
			                                                  "default",
			                                                  "track"
	                                                  },
	                                                  {
			                                                  "defer",
			                                                  "script"
	                                                  },
	                                                  {
			                                                  "dir",
			                                                  "*"
	                                                  },
	                                                  {
			                                                  "dirname",
			                                                  "input",
			                                                  "textarea"
	                                                  },
	                                                  {
			                                                  "disabled",
			                                                  "button",
			                                                  "command",
			                                                  "fieldset",
			                                                  "input",
			                                                  "keygen",
			                                                  "optgroup",
			                                                  "option",
			                                                  "select",
			                                                  "textarea"
	                                                  },
	                                                  {
			                                                  "download",
			                                                  "a",
			                                                  "area"
	                                                  },
	                                                  {
			                                                  "draggable",
			                                                  "*"
	                                                  },
	                                                  {
			                                                  "dropzone",
			                                                  "*"
	                                                  },
	                                                  {
			                                                  "enctype",
			                                                  "form"
	                                                  },
	                                                  {
			                                                  "for",
			                                                  "label",
			                                                  "output"
	                                                  },
	                                                  {
			                                                  "button",
			                                                  "fieldset",
			                                                  "input",
			                                                  "keygen",
			                                                  "label",
			                                                  "meter",
			                                                  "object",
			                                                  "output",
			                                                  "progress",
			                                                  "select",
			                                                  "textarea"
	                                                  },
	                                                  {
			                                                  "formaction",
			                                                  "input",
			                                                  "button"
	                                                  },
	                                                  {
			                                                  "headers",
			                                                  "td",
			                                                  "th"
	                                                  },
	                                                  {
			                                                  "height",
			                                                  "canvas",
			                                                  "embed",
			                                                  "iframe",
			                                                  "img",
			                                                  "object",
			                                                  "video"
	                                                  },
	                                                  {
			                                                  "hidden",
			                                                  "*"
	                                                  },
	                                                  {
			                                                  "high",
			                                                  "meter"
	                                                  },
	                                                  {
			                                                  "href",
			                                                  "area",
			                                                  "a",
			                                                  "base",
			                                                  "link"
	                                                  },
	                                                  {
			                                                  "hreflang",
			                                                  "a",
			                                                  "area",
			                                                  "link"
	                                                  },
	                                                  {
			                                                  "icon",
			                                                  "command"
	                                                  },
	                                                  {
			                                                  "id",
			                                                  "*"
	                                                  },
	                                                  {
			                                                  "integrity",
			                                                  "link",
			                                                  "script"
	                                                  },
	                                                  {
			                                                  "ismap",
			                                                  "img"
	                                                  },
	                                                  {
			                                                  "itemprop",
			                                                  "*"
	                                                  },
	                                                  {
			                                                  "keytype",
			                                                  "keygen"
	                                                  },
	                                                  {
			                                                  "kind",
			                                                  "track"
	                                                  },
	                                                  {
			                                                  "label",
			                                                  "track"
	                                                  },
	                                                  {
			                                                  "loop",
			                                                  "audio",
			                                                  "bgsound",
			                                                  "marquee",
			                                                  "video"
	                                                  },
	                                                  {
			                                                  "low",
			                                                  "meter"
	                                                  },
	                                                  {
			                                                  "manifest",
			                                                  "html"
	                                                  },
	                                                  {
			                                                  "max",
			                                                  "input",
			                                                  "meter",
			                                                  "progress"
	                                                  },
	                                                  {
			                                                  "maclength",
			                                                  "input",
			                                                  "textarea"
	                                                  },
	                                                  {
			                                                  "media",
			                                                  "a",
			                                                  "area",
			                                                  "link",
			                                                  "source",
			                                                  "style"
	                                                  },
	                                                  {
			                                                  "method",
			                                                  "form"
	                                                  },
	                                                  {
			                                                  "min",
			                                                  "input",
			                                                  "meter"
	                                                  },
	                                                  {
			                                                  "muted",
			                                                  "video"
	                                                  },
	                                                  {
			                                                  "name",
			                                                  "button",
			                                                  "form",
			                                                  "fieldset",
			                                                  "iframe",
			                                                  "input",
			                                                  "keygen",
			                                                  "object",
			                                                  "output",
			                                                  "select",
			                                                  "textarea",
			                                                  "map",
			                                                  "meta",
			                                                  "param"
	                                                  },
	                                                  {
			                                                  "novalidate",
			                                                  "form"
	                                                  },
	                                                  {
			                                                  "open",
			                                                  "details"
	                                                  },
	                                                  {
			                                                  "optimum",
			                                                  "meter"
	                                                  },
	                                                  {
			                                                  "pattern",
			                                                  "input"
	                                                  },
	                                                  {
			                                                  "ping",
			                                                  "a",
			                                                  "area"
	                                                  },
	                                                  {
			                                                  "placeholder",
			                                                  "input",
			                                                  "textarea"
	                                                  },
	                                                  {
			                                                  "poster",
			                                                  "video"
	                                                  },
	                                                  {
			                                                  "preload",
			                                                  "audio",
			                                                  "video"
	                                                  },
	                                                  {
			                                                  "radiogroup",
			                                                  "command"
	                                                  },
	                                                  {
			                                                  "readonly",
			                                                  "input",
			                                                  "textarea"
	                                                  },
	                                                  {
			                                                  "rel",
			                                                  "a",
			                                                  "area",
			                                                  "link"
	                                                  },
	                                                  {
			                                                  "required",
			                                                  "input",
			                                                  "select",
			                                                  "textarea"
	                                                  },
	                                                  {
			                                                  "reversed",
			                                                  "ol"
	                                                  },
	                                                  {
			                                                  "rows",
			                                                  "textarea"
	                                                  },
	                                                  {
			                                                  "rowspan",
			                                                  "td",
			                                                  "th"
	                                                  },
	                                                  {
			                                                  "sandbox",
			                                                  "iframe"
	                                                  },
	                                                  {
			                                                  "scope",
			                                                  "th"
	                                                  },
	                                                  {
			                                                  "scoped",
			                                                  "style"
	                                                  },
	                                                  {
			                                                  "seamless",
			                                                  "iframe"
	                                                  },
	                                                  {
			                                                  "selected",
			                                                  "option"
	                                                  },
	                                                  {
			                                                  "shape",
			                                                  "a",
			                                                  "area"
	                                                  },
	                                                  {
			                                                  "size",
			                                                  "input",
			                                                  "select"
	                                                  },
	                                                  {
			                                                  "sizes",
			                                                  "link",
			                                                  "img",
			                                                  "source"
	                                                  },
	                                                  {
			                                                  "slot",
			                                                  "*"
	                                                  },
	                                                  {
			                                                  "span",
			                                                  "col",
			                                                  "colgroup"
	                                                  },
	                                                  {
			                                                  "spellcheck",
			                                                  "*"
	                                                  },
	                                                  {
			                                                  "src",
			                                                  "audio",
			                                                  "embed",
			                                                  "iframe",
			                                                  "img",
			                                                  "input",
			                                                  "script",
			                                                  "source",
			                                                  "track",
			                                                  "video",
			                                                  "style",
			                                                  "link"
	                                                  },
	                                                  {
			                                                  "srcdoc",
			                                                  "iframe"
	                                                  },
	                                                  {
			                                                  "srclang",
			                                                  "track"
	                                                  },
	                                                  {
			                                                  "srcset",
			                                                  "img"
	                                                  },
	                                                  {
			                                                  "start",
			                                                  "ol"
	                                                  },
	                                                  {
			                                                  "step",
			                                                  "input"
	                                                  },
	                                                  {
			                                                  "tabindex",
			                                                  "*"
	                                                  },
	                                                  {
			                                                  "target",
			                                                  "a",
			                                                  "area",
			                                                  "base",
			                                                  "form"
	                                                  },
	                                                  {
			                                                  "title",
			                                                  "*"
	                                                  },
	                                                  {
			                                                  "type",
			                                                  "button",
			                                                  "input",
			                                                  "command",
			                                                  "embed",
			                                                  "object",
			                                                  "script",
			                                                  "source",
			                                                  "style",
			                                                  "menu",
			                                                  "link"
	                                                  },
	                                                  {
			                                                  "usemap",
			                                                  "img",
			                                                  "input",
			                                                  "pbject"
	                                                  },
	                                                  {
			                                                  "value",
			                                                  "button",
			                                                  "options",
			                                                  "input",
			                                                  "li",
			                                                  "meter",
			                                                  "progress",
			                                                  "param"
	                                                  },
	                                                  {
			                                                  "width",
			                                                  "canvas",
			                                                  "embed",
			                                                  "iframe",
			                                                  "img",
			                                                  "input",
			                                                  "object",
			                                                  "video"
	                                                  },
	                                                  {
			                                                  "wrap",
			                                                  "textarea"
	                                                  }
	};
}
